repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: make isort
        language: system
        types: [ python ]
        pass_filenames: false

      - id: black
        name: black
        entry: make black
        language: system
        types: [ python ]
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: make flake8
        language: system
        types: [ python ]
        pass_filenames: false
