services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -h postgres -p 5432" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/database
    ports:
      - ${POSTGRES_PORT}:5432

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data

  celery-worker:
    image: todo-list:latest
    container_name: celery-worker
    env_file: .env
    restart: always
    command: /bin/bash -c "celery -A core worker --loglevel=info"
    depends_on:
      todo-list:
        condition: service_healthy

  celery-beat:
    image: todo-list:latest
    container_name: celery-beat
    env_file: .env
    restart: always
    command: /bin/bash -c "celery -A core beat --loglevel=info"
    depends_on:
      todo-list:
        condition: service_healthy
    volumes:
      - celery-data:/app/celerybeat-schedule

  todo-list:
    image: todo-list:latest
    container_name: todo-list
    env_file: .env
    restart: always
    command: /bin/bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "python", "manage.py", "check" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./:/code/
      - todo-list-logs:/var/log/backend
    ports:
      - ${DJANGO_PORT}:8000

volumes:
  postgres-data: { }
  redis-data: { }
  celery-data: { }
  postgres-logs: { }
  todo-list-logs: { }
