# Generated by Django 5.0.7 on 2024-07-18 17:39

from django.db import migrations

import apps.user.models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_is_email_verified"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.user.models.CustomUserManager()),
            ],
        ),
    ]
